# Generated by Django 4.2.15 on 2024-08-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sense", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="integration_id",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Integration Id"
            ),
        ),
        migrations.AddField(
            model_name="sensor",
            name="integration_type_str",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Integration Type"
            ),
        ),
    ]
