# Generated by Django 4.2.15 on 2024-11-26 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sense", "0002_sensor_sensor_integration_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sensorhistory",
            options={
                "ordering": ["-response_datetime"],
                "verbose_name": "Sensor History",
                "verbose_name_plural": "Sensor History",
            },
        ),
        migrations.RemoveField(
            model_name="sensorhistory",
            name="created_datetime",
        ),
        migrations.AddField(
            model_name="sensorhistory",
            name="response_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Timestamp"
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="sensorhistory",
            index=models.Index(
                fields=["sensor", "-response_datetime"],
                name="sense_senso_sensor__e2513c_idx",
            ),
        ),
    ]
