# Generated by Django 4.2.15 on 2024-11-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sense", "0003_alter_sensorhistory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensorhistory",
            name="integration_extra",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Extra"
            ),
        ),
    ]
