# Generated by Django 4.2.15 on 2024-11-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sense", "0004_sensorhistory_integration_extra"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensorhistory",
            name="integration_extra",
        ),
        migrations.AddField(
            model_name="sensorhistory",
            name="details",
            field=models.TextField(blank=True, null=True, verbose_name="Details"),
        ),
    ]
