# Generated by Django 4.2.22 on 2025-08-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sense", "0004_alter_sensor_integration_payload"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="provides_video_stream",
            field=models.BooleanField(
                default=False, verbose_name="Provides Video Stream"
            ),
        ),
    ]
