# Generated by Django 4.2.15 on 2024-08-28 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sense", "0004_alter_sensor_integration_key"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SensedEntity",
        ),
    ]
