# Generated by Django 4.2.22 on 2025-08-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sense", "0005_sensor_provides_video_stream"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sensorhistory",
            old_name="image_url",
            new_name="source_image_url",
        ),
    ]
