# Generated by Django 4.2.15 on 2024-11-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sense", "0005_remove_sensorhistory_integration_extra_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="persist_history",
            field=models.BooleanField(default=True, verbose_name="Persist History"),
        ),
    ]
