# Generated by Django 4.2.15 on 2024-12-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sense", "0006_sensor_persist_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensorhistory",
            name="response_datetime",
            field=models.DateTimeField(db_index=True, verbose_name="Timestamp"),
        ),
    ]
