# Generated by Django 4.2.22 on 2025-08-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sense", "0006_rename_image_url_to_source_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensorhistory",
            name="has_video_stream",
            field=models.BooleanField(default=False, verbose_name="Has Video Stream"),
        ),
    ]
