# Generated by Django 4.2.15 on 2024-12-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sense", "0007_alter_sensorhistory_response_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensorhistory",
            name="image_url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Image URL"
            ),
        ),
    ]
