# Generated by Django 4.2.22 on 2025-08-24 16:29

import json
from django.db import migrations


def backfill_zoneminder_video_streams(apps, schema_editor):
    """
    Set has_video_stream=True for existing ZoneMinder SensorHistory records
    that have an 'Event Id' in their details JSON.
    """
    SensorHistory = apps.get_model('sense', 'SensorHistory')
    
    # Find all ZoneMinder sensor history records with Event Id in details
    zm_records = SensorHistory.objects.filter(
        sensor__integration_id='zm',
        details__isnull=False
    ).exclude(details='')
    
    updated_count = 0
    
    for record in zm_records:
        try:
            # Parse the details JSON
            details_dict = json.loads(record.details)
            
            # Check if it has an Event Id (ZoneMinder's video stream indicator)
            if 'Event Id' in details_dict:
                record.has_video_stream = True
                record.save(update_fields=['has_video_stream'])
                updated_count += 1
                
        except (json.JSONDecodeError, TypeError):
            # Skip records with invalid JSON
            continue
    
    print(f"Updated {updated_count} ZoneMinder sensor history records with has_video_stream=True")


def reverse_backfill_zoneminder_video_streams(apps, schema_editor):
    """
    Reverse the migration by setting has_video_stream back to False
    for ZoneMinder records.
    """
    SensorHistory = apps.get_model('sense', 'SensorHistory')
    
    updated_count = SensorHistory.objects.filter(
        sensor__integration_id='zm',
        has_video_stream=True
    ).update(has_video_stream=False)
    
    print(f"Reverted {updated_count} ZoneMinder sensor history records to has_video_stream=False")


class Migration(migrations.Migration):

    dependencies = [
        ("sense", "0007_add_has_video_stream_to_sensor_history"),
    ]

    operations = [
        migrations.RunPython(
            backfill_zoneminder_video_streams,
            reverse_backfill_zoneminder_video_streams
        ),
    ]
