# Generated by Django 4.2.24 on 2025-09-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sense", "0008_backfill_zoneminder_has_video_stream"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensorhistory",
            name="video_stream_duration_ms",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Video Stream Duration (ms)"
            ),
        ),
    ]
