# Generated by Django 4.2.15 on 2024-12-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sense", "0008_sensorhistory_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensorhistory",
            name="image_url",
            field=models.TextField(blank=True, null=True, verbose_name="Image URL"),
        ),
    ]
