# Generated by Django 4.2.24 on 2025-09-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sense", "0009_add_video_stream_duration_ms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensorhistory",
            name="video_stream_duration_ms",
        ),
        migrations.AddField(
            model_name="sensorhistory",
            name="correlation_id",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Correlation ID"
            ),
        ),
        migrations.AddField(
            model_name="sensorhistory",
            name="correlation_role_str",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Correlation Role"
            ),
        ),
    ]
