# Generated by Django 4.2.15 on 2024-08-23 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "collection_type_str",
                    models.CharField(max_length=32, verbose_name="Collection Type"),
                ),
                (
                    "svg_path",
                    models.TextField(blank=True, null=True, verbose_name="Path"),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
            },
        ),
        migrations.CreateModel(
            name="CollectionEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.PositiveIntegerField(default=0, verbose_name="Order Id"),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collection.collection",
                        verbose_name="Collection",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entity.entity",
                        verbose_name="Entity",
                    ),
                ),
            ],
            options={
                "ordering": ["order_id"],
                "indexes": [
                    models.Index(
                        fields=["collection", "entity"],
                        name="collection__collect_04e3d8_idx",
                    )
                ],
            },
        ),
    ]
