# Generated by Django 4.2.24 on 2025-09-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="order_id",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Position"
            ),
        ),
        migrations.AlterField(
            model_name="collectionentity",
            name="order_id",
            field=models.PositiveIntegerField(default=0, verbose_name="Position"),
        ),
    ]
