# Generated by Django 4.2.15 on 2024-10-16 20:09

from django.db import migrations
import hi.apps.common.svg_models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionposition",
            name="svg_rotate",
            field=hi.apps.common.svg_models.SvgDecimalField(
                decimal_places=6, default=0.0, max_digits=11, verbose_name="Rotate"
            ),
        ),
        migrations.AlterField(
            model_name="collectionposition",
            name="svg_scale",
            field=hi.apps.common.svg_models.SvgDecimalField(
                decimal_places=6, default=1.0, max_digits=11, verbose_name="Scale"
            ),
        ),
        migrations.AlterField(
            model_name="collectionposition",
            name="svg_x",
            field=hi.apps.common.svg_models.SvgDecimalField(
                decimal_places=6, max_digits=11, verbose_name="X"
            ),
        ),
        migrations.AlterField(
            model_name="collectionposition",
            name="svg_y",
            field=hi.apps.common.svg_models.SvgDecimalField(
                decimal_places=6, max_digits=11, verbose_name="Y"
            ),
        ),
    ]
