# Generated by Django 4.2.15 on 2024-08-28 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "location",
            "0003_locationview_view_type_str_alter_location_order_id_and_more",
        ),
        ("collection", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="svg_path",
        ),
        migrations.CreateModel(
            name="CollectionView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_views",
                        to="collection.collection",
                        verbose_name="Collection",
                    ),
                ),
                (
                    "location_view",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to="location.locationview",
                        verbose_name="Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection View",
                "verbose_name_plural": "Collection Views",
            },
        ),
        migrations.CreateModel(
            name="CollectionPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "svg_x",
                    models.DecimalField(
                        decimal_places=6, max_digits=12, verbose_name="X"
                    ),
                ),
                (
                    "svg_y",
                    models.DecimalField(
                        decimal_places=6, max_digits=12, verbose_name="Y"
                    ),
                ),
                (
                    "svg_scale",
                    models.DecimalField(
                        decimal_places=6,
                        default=1.0,
                        max_digits=12,
                        verbose_name="Scale",
                    ),
                ),
                (
                    "svg_rotation",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Rotation",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="collection.collection",
                        verbose_name="Collection",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_positions",
                        to="location.location",
                        verbose_name="Location",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
