# Generated by Django 4.2.15 on 2024-08-28 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0005_entitypath_updated_datetime_and_more"),
        ("collection", "0002_remove_collection_svg_path_collectionview_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionview",
            name="order_id",
            field=models.PositiveIntegerField(default=0, verbose_name="Order Id"),
        ),
        migrations.AlterField(
            model_name="collectionentity",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities",
                to="collection.collection",
                verbose_name="Collection",
            ),
        ),
        migrations.AlterField(
            model_name="collectionentity",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to="entity.entity",
                verbose_name="Entity",
            ),
        ),
    ]
