# Generated by Django 4.2.15 on 2024-11-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0002_alter_collectionposition_svg_rotate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="collection_view_type_str",
            field=models.CharField(
                default="grid", max_length=32, verbose_name="View Type"
            ),
            preserve_default=False,
        ),
    ]
