# Generated by Django 4.2.15 on 2024-09-01 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0005_rename_svg_rotation_locationview_svg_rotate"),
        ("collection", "0003_collectionview_order_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collectionentity",
            options={
                "ordering": ["order_id"],
                "verbose_name": "Collection Entity",
                "verbose_name_plural": "Collection Entities",
            },
        ),
        migrations.AlterModelOptions(
            name="collectionposition",
            options={
                "verbose_name": "Collection Position",
                "verbose_name_plural": "Collection Positions",
            },
        ),
        migrations.RenameField(
            model_name="collectionposition",
            old_name="svg_rotation",
            new_name="svg_rotate",
        ),
        migrations.AlterField(
            model_name="collectionview",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_views",
                to="collection.collection",
                verbose_name="Collection",
            ),
        ),
        migrations.AlterField(
            model_name="collectionview",
            name="location_view",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_views",
                to="location.locationview",
                verbose_name="Location",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionposition",
            constraint=models.UniqueConstraint(
                fields=("location", "collection"),
                name="collection_position_location_entity",
            ),
        ),
    ]
