# Generated by Django 4.2.15 on 2024-12-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0003_collection_collection_view_type_str"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="order_id",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Order Id"
            ),
        ),
    ]
