# Generated by Django 4.2.15 on 2024-09-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0004_alter_collectionentity_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionposition",
            name="svg_rotate",
            field=models.DecimalField(
                decimal_places=6, default=0.0, max_digits=12, verbose_name="Rotate"
            ),
        ),
    ]
