# Generated by Django 4.2.15 on 2024-10-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0005_alter_collectionposition_svg_rotate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectionview",
            name="order_id",
        ),
        migrations.AddField(
            model_name="collection",
            name="order_id",
            field=models.PositiveIntegerField(default=0, verbose_name="Order Id"),
        ),
    ]
