# Generated by Django 4.2.15 on 2024-10-09 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0007_rename_view_type_str_locationview_location_view_type_str"),
        ("collection", "0006_remove_collectionview_order_id_collection_order_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("svg_path", models.TextField(verbose_name="Path")),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paths",
                        to="collection.collection",
                        verbose_name="Collection",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_paths",
                        to="location.location",
                        verbose_name="Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Path",
                "verbose_name_plural": "Collection Paths",
            },
        ),
        migrations.AddConstraint(
            model_name="collectionpath",
            constraint=models.UniqueConstraint(
                fields=("location", "collection"),
                name="collection_path_location_collection",
            ),
        ),
    ]
