# Generated by Django 4.2.15 on 2024-10-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0007_collectionpath_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={
                "ordering": ["order_id"],
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
            },
        ),
    ]
