# Generated by Django 4.2.15 on 2024-08-14 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "svg_filename",
                    models.CharField(max_length=256, verbose_name="SVG File"),
                ),
                (
                    "svg_viewbox",
                    models.CharField(max_length=64, verbose_name="Viewbox"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Latitude"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Longitude"
                    ),
                ),
                (
                    "elevation_feet",
                    models.DecimalField(
                        decimal_places=3, max_digits=9, verbose_name="Elevation (ft)"
                    ),
                ),
                ("order_id", models.IntegerField(default=0, verbose_name="Order Id")),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.CreateModel(
            name="LocationView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "svg_viewbox",
                    models.CharField(max_length=64, verbose_name="Viewbox"),
                ),
                (
                    "svg_rotation",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Rotation"
                    ),
                ),
                ("order_id", models.IntegerField(default=0, verbose_name="Order Id")),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="location.location",
                        verbose_name="View",
                    ),
                ),
            ],
            options={
                "verbose_name": "View",
                "verbose_name_plural": "Views",
            },
        ),
    ]
