# Generated by Django 4.2.15 on 2024-08-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                decimal_places=8, max_digits=11, verbose_name="Latitude"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                decimal_places=8, max_digits=11, verbose_name="Longitude"
            ),
        ),
    ]
