# Generated by Django 4.2.15 on 2024-10-15 23:02

from django.db import migrations
import hi.apps.common.svg_models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationview",
            name="svg_rotate",
            field=hi.apps.common.svg_models.SvgDecimalField(
                decimal_places=6, max_digits=11, verbose_name="Rotate"
            ),
        ),
    ]
