# Generated by Django 4.2.22 on 2025-08-22 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationAttributeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.TextField(blank=True, null=True, verbose_name="Value"),
                ),
                (
                    "changed_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Changed"
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="location.locationattribute",
                        verbose_name="Location Attribute",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Attribute History",
                "verbose_name_plural": "Location Attribute History",
                "indexes": [
                    models.Index(
                        fields=["attribute", "-changed_datetime"],
                        name="location_lo_attribu_dc1583_idx",
                    )
                ],
            },
        ),
    ]
