# Generated by Django 4.2.15 on 2024-10-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "location",
            "0002_rename_attribute_value_type_str_locationattribute_value_type_str",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationattribute",
            name="value_type_str",
            field=models.CharField(max_length=32, verbose_name="Value Type"),
        ),
    ]
