# Generated by Django 4.2.15 on 2024-10-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0002_alter_locationview_svg_rotate"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationattribute",
            name="file_value",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/attributes/"
            ),
        ),
    ]
