# Generated by Django 4.2.24 on 2025-09-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0002_locationattributehistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="order_id",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Position"
            ),
        ),
        migrations.AlterField(
            model_name="locationview",
            name="order_id",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Position"
            ),
        ),
    ]
