# Generated by Django 4.2.15 on 2024-08-23 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0002_alter_location_latitude_alter_location_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationview",
            name="view_type_str",
            field=models.CharField(
                default="information", max_length=32, verbose_name="View Type"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="location",
            name="order_id",
            field=models.PositiveIntegerField(default=0, verbose_name="Order Id"),
        ),
        migrations.AlterField(
            model_name="locationview",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="location.location",
                verbose_name="Location",
            ),
        ),
        migrations.AlterField(
            model_name="locationview",
            name="order_id",
            field=models.PositiveIntegerField(default=0, verbose_name="Order Id"),
        ),
    ]
