# Generated by Django 4.2.15 on 2024-08-29 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "location",
            "0003_locationview_view_type_str_alter_location_order_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="svg_viewbox",
            new_name="svg_view_box_str",
        ),
        migrations.RenameField(
            model_name="locationview",
            old_name="svg_viewbox",
            new_name="svg_view_box_str",
        ),
    ]
