# Generated by Django 4.2.25 on 2026-01-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0003_alter_location_order_id_alter_locationview_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationattribute",
            name="order_id",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordering Index"),
        ),
    ]
