# Generated by Django 4.2.15 on 2024-10-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0003_locationattribute_file_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationattribute",
            name="file_mime_type",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Mime Type"
            ),
        ),
        migrations.AlterField(
            model_name="locationattribute",
            name="file_value",
            field=models.FileField(blank=True, null=True, upload_to="attributes/"),
        ),
        migrations.AlterField(
            model_name="locationattribute",
            name="value",
            field=models.TextField(blank=True, null=True, verbose_name="Value"),
        ),
    ]
