# Generated by Django 4.2.15 on 2024-11-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0004_locationattribute_file_mime_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationview",
            name="status_display_type_str",
            field=models.CharField(
                default="default", max_length=32, verbose_name="Status Display Type"
            ),
        ),
    ]
