# Generated by Django 4.2.15 on 2024-09-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0005_rename_svg_rotation_locationview_svg_rotate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationview",
            name="svg_rotate",
            field=models.DecimalField(
                decimal_places=6, max_digits=9, verbose_name="Rotate"
            ),
        ),
    ]
