# Generated by Django 4.2.15 on 2024-11-26 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0005_locationview_status_display_type_str"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locationview",
            name="status_display_type_str",
        ),
    ]
