# Generated by Django 4.2.25 on 2026-03-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0005_alter_locationattribute_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationattribute",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Deleted?"
            ),
        ),
    ]
