# Generated by Django 4.2.15 on 2024-12-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0006_remove_locationview_status_display_type_str"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationattribute",
            name="value_range",
            field=models.TextField(blank=True, null=True, verbose_name="Value Range"),
        ),
    ]
