# Generated by Django 4.2.15 on 2024-10-03 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0006_alter_locationview_svg_rotate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="locationview",
            old_name="view_type_str",
            new_name="location_view_type_str",
        ),
    ]
