# Generated by Django 4.2.15 on 2024-10-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0007_rename_view_type_str_locationview_location_view_type_str"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["order_id"],
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.AlterModelOptions(
            name="locationview",
            options={
                "ordering": ["order_id"],
                "verbose_name": "View",
                "verbose_name_plural": "Views",
            },
        ),
        migrations.RemoveField(
            model_name="location",
            name="elevation_feet",
        ),
        migrations.RemoveField(
            model_name="location",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="location",
            name="longitude",
        ),
        migrations.AddField(
            model_name="location",
            name="svg_fragment_filename",
            field=models.FileField(
                default="temp",
                max_length=255,
                upload_to="",
                verbose_name="SVG Filename",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="location",
            name="svg_filename",
            field=models.FileField(upload_to=""),
        ),
    ]
