# Generated by Django 4.2.15 on 2024-10-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0008_alter_location_options_alter_locationview_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="svg_fragment_filename",
            field=models.CharField(max_length=255, verbose_name="SVG Filename"),
        ),
    ]
