# Generated by Django 4.2.15 on 2024-12-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0008_rename_value_range_locationattribute_value_range_str"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="order_id",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Order Id"
            ),
        ),
        migrations.AlterField(
            model_name="locationview",
            name="order_id",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Order Id"
            ),
        ),
    ]
