# Generated by Django 4.2.15 on 2024-10-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0009_alter_location_svg_fragment_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="svg_view_box_str",
            field=models.CharField(max_length=128, verbose_name="Viewbox"),
        ),
    ]
