# Generated by Django 4.2.15 on 2024-10-11 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0012_remove_location_svg_filename"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attribute_value_type_str",
                    models.CharField(
                        max_length=32, verbose_name="Attribute Value Type"
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("value", models.TextField(verbose_name="Value")),
                (
                    "attribute_type_str",
                    models.CharField(max_length=32, verbose_name="Attribute Type"),
                ),
                (
                    "is_editable",
                    models.BooleanField(default=True, verbose_name="Editable?"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Required?"),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="location.location",
                        verbose_name="Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attribute",
                "verbose_name_plural": "Attributes",
                "indexes": [
                    models.Index(
                        fields=["name", "value"], name="location_lo_name_0c26e1_idx"
                    )
                ],
            },
        ),
    ]
