# Generated by Django 5.2.14 on 2026-05-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nws", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nwssimalert",
            name="updated_datetime",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
