# Generated by Django 5.2.14 on 2026-05-19 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("simulator_profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DbSimEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_fields_class_id",
                    models.CharField(
                        max_length=255, verbose_name="Entity Fields Class Id"
                    ),
                ),
                (
                    "sim_entity_type_str",
                    models.CharField(max_length=32, verbose_name="Entity Type"),
                ),
                (
                    "sim_entity_fields_json",
                    models.JSONField(default=dict, verbose_name="Entity Fields"),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "sim_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="db_sim_entities",
                        to="simulator_profile.simprofile",
                        verbose_name="Simulator Profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulator Entity",
                "verbose_name_plural": "Simulator Entities",
            },
        ),
    ]
