# Generated by Django 4.2.15 on 2024-08-25 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("control", "0002_controller_integration_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="controller",
            old_name="integration_id",
            new_name="integration_key",
        ),
    ]
