# Generated by Django 4.2.15 on 2024-12-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control", "0002_controller_controller_integration_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="controller",
            name="persist_history",
            field=models.BooleanField(default=True, verbose_name="Persist History"),
        ),
    ]
