# Generated by Django 4.2.15 on 2024-12-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control", "0003_controller_persist_history"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="controllerhistory",
            options={
                "ordering": ["-created_datetime"],
                "verbose_name": "Controller History",
                "verbose_name_plural": "Controller History",
            },
        ),
        migrations.AlterField(
            model_name="controllerhistory",
            name="created_datetime",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Created"
            ),
        ),
    ]
