# Generated by Django 4.2.25 on 2026-01-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_integrationattributehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationattribute",
            name="order_id",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordering Index"),
        ),
    ]
