# Generated by Django 4.2.25 on 2026-02-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_integrationattribute_order_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="integrationattribute",
            options={
                "ordering": ["order_id", "id"],
                "verbose_name": "Attribute",
                "verbose_name_plural": "Attributes",
            },
        ),
    ]
