# Generated by Django 4.2.29 on 2026-03-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_alter_integrationattribute_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationattribute",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Description"),
        ),
    ]
