# Generated by Django 4.2.24 on 2026-04-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0005_add_integration_attribute_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="is_paused",
            field=models.BooleanField(default=False, verbose_name="Paused?"),
        ),
    ]
