# Generated by Django 4.2.15 on 2025-02-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subsystem",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="subsystem",
            name="subsystem_key",
            field=models.CharField(
                max_length=32, unique=True, verbose_name="Subsystem Key"
            ),
        ),
    ]
