# Generated by Django 4.2.15 on 2024-11-27 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subsystem",
            options={"verbose_name": "Subsystem", "verbose_name_plural": "Subsystems"},
        ),
    ]
