# Generated by Django 4.2.15 on 2025-08-03 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0002_alter_subsystem_name_alter_subsystem_subsystem_key"),
    ]

    operations = []
