# Generated by Django 4.2.25 on 2026-01-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0004_subsystemattributehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsystemattribute",
            name="order_id",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordering Index"),
        ),
    ]
