# Generated by Django 4.2.15 on 2024-12-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0004_rename_value_range_subsystemattribute_value_range_str"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsystemattribute",
            name="subsystem_attribute_type_str",
            field=models.CharField(
                default="foo", max_length=32, verbose_name="Subsystem Attribute Type"
            ),
            preserve_default=False,
        ),
    ]
