# Generated by Django 4.2.24 on 2025-11-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0004_subsystemattributehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsystemattribute",
            name="ordering_index",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordering Index"),
        ),
    ]
