# Generated by Django 4.2.25 on 2026-02-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0005_subsystemattribute_order_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subsystemattribute",
            options={
                "ordering": ["order_id", "id"],
                "verbose_name": "Subsystem Attribute",
                "verbose_name_plural": "Subsystem Attributes",
            },
        ),
    ]
