# Generated by Django 4.2.15 on 2024-12-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0005_subsystemattribute_subsystem_attribute_type_str"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subsystemattribute",
            name="subsystem_attribute_type_str",
            field=models.CharField(
                max_length=255, verbose_name="Subsystem Attribute Type"
            ),
        ),
    ]
