# Generated by Django 4.2.15 on 2024-12-12 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0006_alter_subsystemattribute_subsystem_attribute_type_str"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subsystem",
            old_name="subsystem_type_str",
            new_name="subsystem_key",
        ),
        migrations.RenameField(
            model_name="subsystemattribute",
            old_name="subsystem_attribute_type_str",
            new_name="setting_key",
        ),
    ]
