# Generated by Django 4.2.15 on 2024-12-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0007_rename_subsystem_type_str_subsystem_subsystem_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subsystem",
            name="subsystem_key",
            field=models.CharField(max_length=32, verbose_name="Subsystem Key"),
        ),
        migrations.AlterField(
            model_name="subsystemattribute",
            name="setting_key",
            field=models.CharField(max_length=255, verbose_name="Setting Key"),
        ),
    ]
