# Generated by Django 5.2.14 on 2026-05-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module_key",
                    models.CharField(max_length=96, verbose_name="Module Key"),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Profile Name")),
                (
                    "last_switched_to_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Switched To"
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
            ],
            options={
                "ordering": ["module_key", "name"],
                "unique_together": {("module_key", "name")},
            },
        ),
    ]
