# Generated by Django 4.2.15 on 2024-10-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatabaseLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("acquired_at", models.DateTimeField()),
                ("initialized", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Database Lock",
                "verbose_name_plural": "Database Locks",
            },
        ),
    ]
