# Generated by Django 4.2.15 on 2024-08-23 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="databaselock",
            options={
                "verbose_name": "Database Lock",
                "verbose_name_plural": "Database Locks",
            },
        ),
    ]
