# Generated by Django 4.2.15 on 2024-08-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_databaselock_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="databaselock",
            name="initialized",
            field=models.BooleanField(default=False),
        ),
    ]
