# Generated by Django 5.2.14 on 2026-05-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NwsSimAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Include this alert in the simulated active-alerts feed.",
                    ),
                ),
                (
                    "event_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "— None —"),
                            ("TOR", "TOR — Tornado Warning"),
                            ("TOA", "TOA — Tornado Watch"),
                            ("SVR", "SVR — Severe Thunderstorm Warning"),
                            ("SVA", "SVA — Severe Thunderstorm Watch"),
                            ("FFW", "FFW — Flash Flood Warning"),
                            ("FFA", "FFA — Flash Flood Watch"),
                            ("FLW", "FLW — Flood Warning"),
                            ("FLA", "FLA — Flood Watch"),
                            ("EWW", "EWW — Extreme Wind Warning"),
                            ("HWW", "HWW — High Wind Warning"),
                            ("BZW", "BZW — Blizzard Warning"),
                            ("WSW", "WSW — Winter Storm Warning"),
                            ("WSA", "WSA — Winter Storm Watch"),
                            ("HUW", "HUW — Hurricane Warning"),
                            ("HUA", "HUA — Hurricane Watch"),
                            ("TRW", "TRW — Tropical Storm Warning"),
                            ("TRA", "TRA — Tropical Storm Watch"),
                            ("TSW", "TSW — Tsunami Warning"),
                            ("TSA", "TSA — Tsunami Watch"),
                            ("FRW", "FRW — Fire Warning"),
                            ("RFW", "RFW — Red Flag Warning"),
                            ("AFW", "AFW — Ashfall Warning"),
                            ("EQW", "EQW — Earthquake Warning"),
                            ("AQA", "AQA — Air Quality Alert"),
                            ("CDW", "CDW — Civil Danger Warning"),
                            ("CEM", "CEM — Civil Emergency Message"),
                            ("LAE", "LAE — Local Area Emergency"),
                            ("TST", "TST — Test Message"),
                        ],
                        default="",
                        help_text="NWS three-letter event code (drives main-app event type mapping).",
                        max_length=8,
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        default="Test Alert",
                        help_text='Human-readable event name (e.g. "Air Quality Alert").',
                        max_length=128,
                    ),
                ),
                (
                    "severity_str",
                    models.CharField(
                        choices=[
                            ("Extreme", "Extreme"),
                            ("Severe", "Severe"),
                            ("Moderate", "Moderate"),
                            ("Minor", "Minor"),
                            ("Unknown", "Unknown"),
                        ],
                        default="Minor",
                        max_length=16,
                    ),
                ),
                (
                    "certainty_str",
                    models.CharField(
                        choices=[
                            ("Observed", "Observed"),
                            ("Likely", "Likely"),
                            ("Possible", "Possible"),
                            ("Unlikely", "Unlikely"),
                            ("Unknown", "Unknown"),
                        ],
                        default="Possible",
                        max_length=16,
                    ),
                ),
                (
                    "urgency_str",
                    models.CharField(
                        choices=[
                            ("Immediate", "Immediate"),
                            ("Expected", "Expected"),
                            ("Future", "Future"),
                            ("Unknown", "Unknown"),
                        ],
                        default="Expected",
                        max_length=16,
                    ),
                ),
                (
                    "status_str",
                    models.CharField(
                        choices=[
                            ("Actual", "Actual"),
                            ("Exercise", "Exercise"),
                            ("System", "System"),
                            ("Test", "Test"),
                            ("Draft", "Draft"),
                        ],
                        default="Actual",
                        max_length=16,
                    ),
                ),
                (
                    "category_str",
                    models.CharField(
                        choices=[
                            ("met", "Meteorological"),
                            ("geo", "Geological"),
                            ("safety", "Public Safety"),
                            ("security", "Security"),
                            ("rescue", "Rescue"),
                            ("fire", "Fire"),
                            ("health", "Health"),
                            ("env", "Environmental"),
                            ("transport", "Transportation"),
                            ("infra", "Infrastructure"),
                            ("other", "Other"),
                        ],
                        default="met",
                        max_length=16,
                    ),
                ),
                ("headline", models.CharField(default="", max_length=512)),
                ("description", models.TextField(default="")),
                ("instruction", models.TextField(blank=True, default="")),
                (
                    "area_desc",
                    models.CharField(
                        default="ServiceSimulator Test Area", max_length=255
                    ),
                ),
                (
                    "effective_offset_secs",
                    models.IntegerField(
                        default=-60,
                        help_text='When the alert becomes effective, relative to "now" in seconds. Negative = in the past, positive = in the future.',
                    ),
                ),
                (
                    "expires_offset_secs",
                    models.IntegerField(
                        default=3600,
                        help_text='When the alert expires, relative to "now" in seconds.',
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "NWS Sim Alert",
                "verbose_name_plural": "NWS Sim Alerts",
                "ordering": ["-created_datetime"],
            },
        ),
    ]
