# Generated by Django 4.2.15 on 2024-12-19 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("control", "0001_initial"),
        ("entity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "integration_id",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="Integration Id",
                    ),
                ),
                (
                    "integration_name",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Integration Name",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "event_type_str",
                    models.CharField(max_length=32, verbose_name="Event Type"),
                ),
                (
                    "event_window_secs",
                    models.PositiveIntegerField(verbose_name="Event Window Secs"),
                ),
                (
                    "dedupe_window_secs",
                    models.PositiveIntegerField(verbose_name="Dedupe Window Secs"),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
            ],
            options={
                "verbose_name": "Event Definition",
                "verbose_name_plural": "Event Definitions",
            },
        ),
        migrations.CreateModel(
            name="EventHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_datetime",
                    models.DateTimeField(db_index=True, verbose_name="Timestamp"),
                ),
                (
                    "event_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="event.eventdefinition",
                        verbose_name="Event Definition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event History",
                "verbose_name_plural": "Event History",
                "ordering": ["-event_datetime"],
            },
        ),
        migrations.CreateModel(
            name="EventClause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255, verbose_name="Value")),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "entity_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="entity.entitystate",
                        verbose_name="Entity State",
                    ),
                ),
                (
                    "event_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_clauses",
                        to="event.eventdefinition",
                        verbose_name="Event Definition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Clause",
                "verbose_name_plural": "Event Clauses",
            },
        ),
        migrations.CreateModel(
            name="ControlAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255, verbose_name="Value")),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "controller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_actions",
                        to="control.controller",
                        verbose_name="Controller",
                    ),
                ),
                (
                    "event_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_actions",
                        to="event.eventdefinition",
                        verbose_name="Event Definition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Control Action",
                "verbose_name_plural": "Control Actions",
            },
        ),
        migrations.CreateModel(
            name="AlarmAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "security_level_str",
                    models.CharField(max_length=32, verbose_name="Security Level"),
                ),
                (
                    "alarm_level_str",
                    models.CharField(max_length=32, verbose_name="Alarm Level"),
                ),
                (
                    "alarm_lifetime_secs",
                    models.PositiveIntegerField(verbose_name="Lifetime Secs"),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "event_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarm_actions",
                        to="event.eventdefinition",
                        verbose_name="Event Definition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alarm Actions",
                "verbose_name_plural": "Alarm Actions",
            },
        ),
    ]
