# Generated by Django 4.2.15 on 2025-08-15 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_add_integration_metadata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventdefinition",
            old_name="integration_metadata",
            new_name="integration_payload",
        ),
    ]
