# Generated by Django 4.2.15 on 2024-12-05 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_eventdefinition_integration_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alarmaction",
            old_name="lifetime_secs",
            new_name="alarm_lifetime_secs",
        ),
    ]
