# Generated by Django 4.2.15 on 2025-08-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "event",
            "0003_rename_integration_metadata_eventdefinition_integration_payload",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventdefinition",
            name="integration_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Integration-specific data (e.g., HA domain, device capabilities)",
                verbose_name="Integration Payload",
            ),
        ),
    ]
