# Generated by Django 4.2.15 on 2024-12-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_rename_lifetime_secs_alarmaction_alarm_lifetime_secs"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdefinition",
            name="dedupe_window_secs",
            field=models.PositiveIntegerField(
                default=300, verbose_name="Desupe Window Secs"
            ),
            preserve_default=False,
        ),
    ]
