# Generated by Django 4.2.15 on 2025-09-07 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_alter_eventdefinition_integration_payload"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventclause",
            options={
                "verbose_name": "Trigger Clause",
                "verbose_name_plural": "Trigger Clauses",
            },
        ),
        migrations.AlterModelOptions(
            name="eventdefinition",
            options={
                "verbose_name": "Trigger Definition",
                "verbose_name_plural": "Trigger Definitions",
            },
        ),
        migrations.AlterModelOptions(
            name="eventhistory",
            options={
                "ordering": ["-event_datetime"],
                "verbose_name": "Trigger History",
                "verbose_name_plural": "Trigger History",
            },
        ),
        migrations.AlterField(
            model_name="alarmaction",
            name="event_definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alarm_actions",
                to="event.eventdefinition",
                verbose_name="Trigger Definition",
            ),
        ),
        migrations.AlterField(
            model_name="controlaction",
            name="event_definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="control_actions",
                to="event.eventdefinition",
                verbose_name="Trigger Definition",
            ),
        ),
        migrations.AlterField(
            model_name="eventclause",
            name="event_definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_clauses",
                to="event.eventdefinition",
                verbose_name="Trigger Definition",
            ),
        ),
        migrations.AlterField(
            model_name="eventdefinition",
            name="event_type_str",
            field=models.CharField(max_length=32, verbose_name="Trigger Type"),
        ),
        migrations.AlterField(
            model_name="eventdefinition",
            name="event_window_secs",
            field=models.PositiveIntegerField(verbose_name="Trigger Window Secs"),
        ),
        migrations.AlterField(
            model_name="eventhistory",
            name="event_definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="event.eventdefinition",
                verbose_name="Trigger Definition",
            ),
        ),
    ]
