# Generated by Django 4.2.15 on 2024-12-06 01:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_eventdefinition_dedupe_window_secs"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarmaction",
            name="created_datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="alarmaction",
            name="updated_datetime",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
        migrations.AddField(
            model_name="controlaction",
            name="updated_datetime",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
    ]
