# Generated by Django 4.2.15 on 2024-12-06 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0006_alter_eventclause_event_definition"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventhistory",
            options={
                "ordering": ["-event_datetime"],
                "verbose_name": "Event History",
                "verbose_name_plural": "Event History",
            },
        ),
    ]
