# Generated by Django 4.2.15 on 2024-12-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0007_alter_eventhistory_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventhistory",
            name="event_datetime",
            field=models.DateTimeField(db_index=True, verbose_name="Timestamp"),
        ),
    ]
