# Generated by Django 4.2.30 on 2026-05-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0007_replace_zero_alarm_lifetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventclause",
            name="value_operator_str",
            field=models.CharField(default="eq", max_length=8, verbose_name="Operator"),
        ),
    ]
