# Generated by Django 4.2.15 on 2024-12-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0008_alter_eventhistory_event_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdefinition",
            name="event_type_str",
            field=models.CharField(
                default="security", max_length=32, verbose_name="Event Type"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="eventdefinition",
            name="dedupe_window_secs",
            field=models.PositiveIntegerField(verbose_name="Dedupe Window Secs"),
        ),
    ]
