# Generated by Django 4.2.15 on 2024-12-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0009_eventdefinition_event_type_str_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alarmaction",
            name="security_posture_str",
        ),
        migrations.AddField(
            model_name="alarmaction",
            name="security_level_str",
            field=models.CharField(
                default="high", max_length=32, verbose_name="Security Level"
            ),
            preserve_default=False,
        ),
    ]
