# Generated by Django 4.2.15 on 2024-08-23 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "location",
            "0003_locationview_view_type_str_alter_location_order_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "entity_type_str",
                    models.CharField(max_length=32, verbose_name="Type"),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
            ],
            options={
                "verbose_name": "Entity",
                "verbose_name_plural": "Entities",
            },
        ),
        migrations.CreateModel(
            name="EntityState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_state_type_str",
                    models.CharField(max_length=32, verbose_name="State Type"),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("value_range", models.TextField(verbose_name="Value Range")),
                (
                    "units",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="Units"
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="entity.entity",
                        verbose_name="Entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity State",
                "verbose_name_plural": "Entity States",
            },
        ),
        migrations.CreateModel(
            name="EntityPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "svg_x",
                    models.DecimalField(
                        decimal_places=6, max_digits=12, verbose_name="X"
                    ),
                ),
                (
                    "svg_y",
                    models.DecimalField(
                        decimal_places=6, max_digits=12, verbose_name="Y"
                    ),
                ),
                (
                    "svg_scale",
                    models.DecimalField(
                        decimal_places=6,
                        default=1.0,
                        max_digits=12,
                        verbose_name="Scale",
                    ),
                ),
                (
                    "svg_rotation",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Rotation",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="entity.entity",
                        verbose_name="Entity",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="location.location",
                        verbose_name="Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Position",
                "verbose_name_plural": "Entity Positions",
                "indexes": [
                    models.Index(
                        fields=["location", "entity"],
                        name="entity_enti_locatio_0402a2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EntityPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("svg_path", models.TextField(verbose_name="Path")),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paths",
                        to="entity.entity",
                        verbose_name="Entity",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paths",
                        to="location.location",
                        verbose_name="Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Path",
                "verbose_name_plural": "Entity Paths",
                "indexes": [
                    models.Index(
                        fields=["location", "entity"],
                        name="entity_enti_locatio_15cbf9_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attribute_value_type_str",
                    models.CharField(
                        max_length=32, verbose_name="Attribute Value Type"
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("value", models.TextField(verbose_name="Value")),
                (
                    "attribute_type_str",
                    models.CharField(max_length=32, verbose_name="Attribute Type"),
                ),
                (
                    "is_editable",
                    models.BooleanField(default=True, verbose_name="Editable?"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Required?"),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="entity.entity",
                        verbose_name="Entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attribute",
                "verbose_name_plural": "Attributes",
                "indexes": [
                    models.Index(
                        fields=["name", "value"], name="entity_attr_name_820790_idx"
                    )
                ],
            },
        ),
    ]
