# Generated by Django 4.2.15 on 2024-10-16 20:09

from django.db import migrations, models
import hi.apps.common.svg_models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entityattribute",
            name="file_value",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/attributes/"
            ),
        ),
        migrations.AlterField(
            model_name="entityposition",
            name="svg_rotate",
            field=hi.apps.common.svg_models.SvgDecimalField(
                decimal_places=6, default=0.0, max_digits=11, verbose_name="Rotate"
            ),
        ),
        migrations.AlterField(
            model_name="entityposition",
            name="svg_scale",
            field=hi.apps.common.svg_models.SvgDecimalField(
                decimal_places=6, default=1.0, max_digits=11, verbose_name="Scale"
            ),
        ),
        migrations.AlterField(
            model_name="entityposition",
            name="svg_x",
            field=hi.apps.common.svg_models.SvgDecimalField(
                decimal_places=6, max_digits=11, verbose_name="X"
            ),
        ),
        migrations.AlterField(
            model_name="entityposition",
            name="svg_y",
            field=hi.apps.common.svg_models.SvgDecimalField(
                decimal_places=6, max_digits=11, verbose_name="Y"
            ),
        ),
    ]
