# Generated by Django 4.2.15 on 2025-08-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="integration_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Integration-specific metadata (e.g., HA domain, device capabilities)",
                verbose_name="Integration Metadata",
            ),
        ),
    ]
