# Generated by Django 4.2.15 on 2024-08-25 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0002_entity_integration_id_entity_integration_type_str_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entity",
            old_name="integration_id",
            new_name="integration_key",
        ),
    ]
