# Generated by Django 4.2.15 on 2024-11-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0003_entityattribute_file_mime_type_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="entity",
            constraint=models.UniqueConstraint(
                fields=("integration_id", "integration_name"),
                name="entity_integration_key",
            ),
        ),
    ]
