# Generated by Django 4.2.15 on 2024-12-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0004_entity_entity_integration_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="entityattribute",
            name="value_range",
            field=models.TextField(blank=True, null=True, verbose_name="Value Range"),
        ),
    ]
