# Generated by Django 4.2.15 on 2024-08-28 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "location",
            "0003_locationview_view_type_str_alter_location_order_id_and_more",
        ),
        ("entity", "0004_alter_entity_integration_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="entitypath",
            name="updated_datetime",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
        migrations.AlterField(
            model_name="entityposition",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entity_positions",
                to="location.location",
                verbose_name="Location",
            ),
        ),
        migrations.CreateModel(
            name="ProxyState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proxy_by_states",
                        to="entity.entity",
                        verbose_name="Entity",
                    ),
                ),
                (
                    "entity_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proxy_for_entities",
                        to="entity.entitystate",
                        verbose_name="Entity State",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntityView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_views",
                        to="entity.entity",
                        verbose_name="Entity",
                    ),
                ),
                (
                    "location_view",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="location.locationview",
                        verbose_name="Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity View",
                "verbose_name_plural": "Entity Views",
            },
        ),
    ]
