# Generated by Django 4.2.22 on 2025-08-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0005_entityattributehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="has_video_stream",
            field=models.BooleanField(default=False, verbose_name="Has Video Stream"),
        ),
    ]
