# Generated by Django 4.2.15 on 2024-09-01 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0005_rename_svg_rotation_locationview_svg_rotate"),
        ("entity", "0005_entitypath_updated_datetime_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="entitypath",
            name="entity_enti_locatio_15cbf9_idx",
        ),
        migrations.RemoveIndex(
            model_name="entityposition",
            name="entity_enti_locatio_0402a2_idx",
        ),
        migrations.RenameField(
            model_name="entityposition",
            old_name="svg_rotation",
            new_name="svg_rotate",
        ),
        migrations.AlterField(
            model_name="entitystate",
            name="value_range",
            field=models.TextField(blank=True, null=True, verbose_name="Value Range"),
        ),
        migrations.AlterField(
            model_name="entityview",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entity_views",
                to="entity.entity",
                verbose_name="Entity",
            ),
        ),
        migrations.AlterField(
            model_name="entityview",
            name="location_view",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entity_views",
                to="location.locationview",
                verbose_name="Location",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitypath",
            constraint=models.UniqueConstraint(
                fields=("location", "entity"), name="entity_path_location_entity"
            ),
        ),
        migrations.AddConstraint(
            model_name="entityposition",
            constraint=models.UniqueConstraint(
                fields=("location", "entity"), name="entity_position_location_entity"
            ),
        ),
    ]
