# Generated by Django 4.2.15 on 2024-10-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0007_alter_entityposition_svg_rotate"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="entityview",
            constraint=models.UniqueConstraint(
                fields=("entity", "location_view"),
                name="entity_view_entity_location_view",
            ),
        ),
    ]
