# Generated by Django 4.2.24 on 2025-09-11 15:28

from django.db import migrations


def fix_multivalued_typo(apps, schema_editor):
    """Fix typo: change 'multivalued' to 'multivalued' in entity_state_type_str"""
    EntityState = apps.get_model('entity', 'EntityState')
    EntityState.objects.filter(entity_state_type_str='multivalued').update(
        entity_state_type_str='multivalued'
    )


def reverse_fix_multivalued_typo(apps, schema_editor):
    """Reverse fix: change 'multivalued' back to 'multivalued'"""
    EntityState = apps.get_model('entity', 'EntityState')
    EntityState.objects.filter(entity_state_type_str='multivalued').update(
        entity_state_type_str='multivalued'
    )


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0007_video_stream_data_migration"),
    ]

    operations = [
        migrations.RunPython(
            fix_multivalued_typo,
            reverse_fix_multivalued_typo,
        ),
    ]
