# Generated by Django 4.2.24 on 2025-11-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0008_fix_multvalued_typo"),
    ]

    operations = [
        migrations.AddField(
            model_name="entityattribute",
            name="ordering_index",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordering Index"),
        ),
    ]
