# Generated by Django 4.2.15 on 2024-10-07 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0009_entitystateproxy_delete_proxystate"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityStateDelegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "delegate_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_state_delegations",
                        to="entity.entity",
                        verbose_name="Deleage Entity",
                    ),
                ),
                (
                    "entity_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_state_delegations",
                        to="entity.entitystate",
                        verbose_name="Entity State",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="EntityStateProxy",
        ),
    ]
