# Generated by Django 4.2.25 on 2026-02-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0009_entityattribute_order_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entityattribute",
            options={
                "ordering": ["order_id", "id"],
                "verbose_name": "Attribute",
                "verbose_name_plural": "Attributes",
            },
        ),
    ]
