# Generated by Django 4.2.25 on 2026-02-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0010_alter_entityattribute_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="can_add_custom_attributes",
            field=models.BooleanField(default=True, verbose_name="Can Add Attributes?"),
        ),
    ]
