# Generated by Django 4.2.15 on 2024-10-09 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0007_rename_view_type_str_locationview_location_view_type_str"),
        ("entity", "0010_entitystatedelegation_delete_entitystateproxy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entitystatedelegation",
            options={
                "verbose_name": "Entity State Delegation",
                "verbose_name_plural": "Entity State Delegations",
            },
        ),
        migrations.AlterField(
            model_name="entitypath",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entity_paths",
                to="location.location",
                verbose_name="Location",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitystatedelegation",
            constraint=models.UniqueConstraint(
                fields=("delegate_entity", "entity_state"),
                name="entity_state_delegation_uniqueness",
            ),
        ),
    ]
