# Generated by Django 4.2.15 on 2024-10-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0011_alter_entitystatedelegation_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Attribute",
            new_name="EntityAttribute",
        ),
        migrations.RenameIndex(
            model_name="entityattribute",
            new_name="entity_enti_name_ca029b_idx",
            old_name="entity_attr_name_820790_idx",
        ),
    ]
