# Generated by Django 4.2.29 on 2026-03-28 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0012_add_entityattribute_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "entity_type_str",
                    models.CharField(max_length=32, verbose_name="Entity Type"),
                ),
                (
                    "original_created_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Originally Created"
                    ),
                ),
                (
                    "archived_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Archived"),
                ),
            ],
            options={
                "verbose_name": "Archived Entity",
                "verbose_name_plural": "Archived Entities",
                "ordering": ["-archived_datetime"],
            },
        ),
        migrations.CreateModel(
            name="ArchivedEntityAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "value",
                    models.TextField(blank=True, null=True, verbose_name="Value"),
                ),
                (
                    "file_value",
                    models.FileField(blank=True, null=True, upload_to="attributes/"),
                ),
                (
                    "file_mime_type",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Mime Type"
                    ),
                ),
                (
                    "value_type_str",
                    models.CharField(max_length=32, verbose_name="Value Type"),
                ),
                (
                    "value_range_str",
                    models.TextField(blank=True, null=True, verbose_name="Value Range"),
                ),
                (
                    "integration_key_str",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Integration Key",
                    ),
                ),
                (
                    "attribute_type_str",
                    models.CharField(max_length=32, verbose_name="Attribute Type"),
                ),
                (
                    "is_editable",
                    models.BooleanField(default=True, verbose_name="Editable?"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Required?"),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "order_id",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordering Index"
                    ),
                ),
                (
                    "archived_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="entity.archivedentity",
                        verbose_name="Archived Entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archived Attribute",
                "verbose_name_plural": "Archived Attributes",
                "ordering": ["order_id", "id"],
            },
        ),
    ]
