# Generated by Django 4.2.24 on 2026-04-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0013_add_archived_entity"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="is_disabled",
            field=models.BooleanField(
                default=False,
                help_text='When True, capabilities the entity would normally provide are suppressed. Used by the integration disconnect path and any future user-initiated "disable" UX.',
                verbose_name="Disabled?",
            ),
        ),
    ]
