# Generated by Django 4.2.24 on 2026-05-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0014_add_entity_is_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="previous_integration_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=32,
                null=True,
                verbose_name="Previous Integration Id",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="previous_integration_name",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Previous Integration Name",
            ),
        ),
    ]
