# Generated by Django 5.2.14 on 2026-05-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0016_add_entity_state_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="has_video_snapshot",
            field=models.BooleanField(
                default=False,
                help_text="Whether the source integration can provide a still image of this entity (e.g., HA camera entity_picture, ZM nph-zms mode=single). Orthogonal to has_video_stream — an entity may provide either, both, or neither capability.",
                verbose_name="Has Video Snapshot",
            ),
        ),
    ]
