# Generated by Django 5.2.14 on 2026-05-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0018_backfill_zoneminder_has_video_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="video_snapshot_stream_fps",
            field=models.FloatField(
                blank=True,
                default=1.0,
                help_text="When has_video_snapshot is True, the rate at which the snapshot is suitable to be polled to approximate a live feed. None or 0 means snapshot exists but is not suitable for synthetic streaming.",
                null=True,
                verbose_name="Video Snapshot Stream FPS",
            ),
        ),
    ]
