# Generated by Django 4.2.15 on 2024-12-20 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, unique=True, verbose_name="Name"),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
            ],
            options={
                "verbose_name": "Simulator Profile",
                "verbose_name_plural": "Simulator Profiles",
            },
        ),
        migrations.CreateModel(
            name="DbSimEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "simulator_id",
                    models.CharField(max_length=64, verbose_name="Simulator Id"),
                ),
                (
                    "entity_class_name",
                    models.CharField(max_length=255, verbose_name="Entity Class Name"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "entity_type_str",
                    models.CharField(max_length=32, verbose_name="Entity Type"),
                ),
                (
                    "extra_fields",
                    models.JSONField(default=dict, verbose_name="Extra Fields"),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "sim_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="db_sim_entities",
                        to="simulator.simprofile",
                        verbose_name="Simulator Profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulator Entity",
                "verbose_name_plural": "Simulator Entities",
            },
        ),
    ]
