# Generated by Django 4.2.15 on 2024-12-21 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simprofile",
            options={
                "ordering": ["-last_switched_to_datetime"],
                "verbose_name": "Simulator Profile",
                "verbose_name_plural": "Simulator Profiles",
            },
        ),
        migrations.AddField(
            model_name="simprofile",
            name="last_switched_to_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Last Switched To"
            ),
            preserve_default=False,
        ),
    ]
