# Generated by Django 4.2.15 on 2024-12-21 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0002_alter_simprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simprofile",
            name="last_switched_to_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Last Switched To"
            ),
        ),
    ]
