# Generated by Django 4.2.15 on 2024-12-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0003_alter_simprofile_last_switched_to_datetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dbsimentity",
            name="extra_fields",
        ),
        migrations.AddField(
            model_name="dbsimentity",
            name="editable_fields",
            field=models.JSONField(default=dict, verbose_name="Editable Fields"),
        ),
    ]
