# Generated by Django 4.2.15 on 2024-12-23 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0004_remove_dbsimentity_extra_fields_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dbsimentity",
            name="name",
        ),
    ]
