# Generated by Django 4.2.15 on 2024-12-24 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0005_remove_dbsimentity_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dbsimentity",
            old_name="entity_class_name",
            new_name="entity_class_id",
        ),
    ]
