# Generated by Django 4.2.15 on 2024-12-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0006_rename_entity_class_name_dbsimentity_entity_class_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbsimentity",
            name="entity_class_id",
            field=models.CharField(max_length=255, verbose_name="Entity Class Id"),
        ),
    ]
