# Generated by Django 4.2.15 on 2024-12-27 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0007_alter_dbsimentity_entity_class_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dbsimentity",
            old_name="editable_fields",
            new_name="entity_fields_str",
        ),
    ]
