# Generated by Django 4.2.15 on 2024-12-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0008_rename_editable_fields_dbsimentity_entity_fields_str"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbsimentity",
            name="entity_fields_str",
            field=models.JSONField(default=dict, verbose_name="Entity Fields"),
        ),
    ]
