# Generated by Django 4.2.15 on 2024-12-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0009_alter_dbsimentity_entity_fields_str"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dbsimentity",
            name="entity_fields_str",
        ),
        migrations.AddField(
            model_name="dbsimentity",
            name="sim_entity_fields_str",
            field=models.JSONField(default=dict, verbose_name="Sim Entity Fields"),
        ),
    ]
