# Generated by Django 4.2.15 on 2024-12-28 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0010_remove_dbsimentity_entity_fields_str_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dbsimentity",
            old_name="entity_class_id",
            new_name="entity_fields_class_id",
        ),
        migrations.RenameField(
            model_name="dbsimentity",
            old_name="sim_entity_fields_str",
            new_name="sim_entity_fields_json",
        ),
    ]
