# Generated by Django 4.2.15 on 2024-12-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0012_alter_dbsimentity_entity_fields_class_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dbsimentity",
            old_name="entity_type_str",
            new_name="sim_entity_type_str",
        ),
    ]
