# Generated by Django 4.2.15 on 2024-12-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0013_rename_entity_type_str_dbsimentity_sim_entity_type_str"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbsimentity",
            name="sim_entity_fields_json",
            field=models.JSONField(default=dict, verbose_name="Entity Fields"),
        ),
    ]
