[supervisord]
user=root
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
loglevel=info
pidfile = /opt/supervisor.d/supervisord.pid

[program:redis]
user=nginx
command=/usr/bin/redis-server
autostart=true
autorestart=true
stdout_syslog=true
stderr_syslog=true
priority=10


[program:wsgi_gunicorn]
user=nginx
command=/src/bin/docker-start-gunicorn.sh
directory=/src
stdout_syslog=true
stderr_syslog=true
stopsignal=KILL
stopasgroup=true  
autostart=true
autorestart=true
priority=20

[program:nginx]
user=root
command=/usr/sbin/nginx -g "daemon off;"
priority=900
stdout_syslog=true
stderr_syslog=true
autostart=true
autorestart=true
priority=30
