# Generated by Django 4.2.15 on 2024-10-12 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_integrationattribute_delete_integrationproperty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="integrationattribute",
            old_name="attribute_value_type_str",
            new_name="value_type_str",
        ),
    ]
