# Generated by Django 4.2.15 on 2024-12-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_integrationattribute_file_mime_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationattribute",
            name="value_range",
            field=models.TextField(blank=True, null=True, verbose_name="Value Range"),
        ),
    ]
