name: Create Release Assets

on:
  release:
    types: [published]

jobs:
  create-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Create source archive using git archive
        run: |
          # Use git archive to create a clean zip that respects .gitignore
          # Add version prefix so it unzips into a versioned directory
          VERSION=${GITHUB_REF#refs/tags/}
          git archive --format=zip --prefix=home-information-${VERSION}/ --output=home-information.zip HEAD
            
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./home-information.zip
          asset_name: home-information.zip
          asset_content_type: application/zip